### PR TITLE
add hidden property in RankFieldConfig interface

### PR DESCRIPTION
**Pull request by plcdnl**

### CODE REVIEW

**Comment by ryami333** [comment]
This is a band-aid fix which doesn't address the underlying issue, which is that this type doesn't reflect the source-of-truth type. As I suggested in the linked issue, a more appropriate fix would be `export interface RankFieldConfig extends SingleFieldSet { … }`

**Comment by michaelmannucci** [comment]
Forgive me for my ignorance, but how do I implement this fix?

**Comment by ryami333** [comment]
@michaelmannucci Bump to the latest version of `@sanity/orderable-document-list`.

**Comment by michaelmannucci** [comment]
@ryami333 Thanks for the quick reply. I am on `"@sanity/orderable-document-list": "^1.2.1",`, is that not latest?

**Pull request closed without merging**
